version: '2'
services:
  dnsmasq:
    container_name: local_dnsserver
    image: andyshinn/dnsmasq
    ports:
    - "53/tcp:53/tcp"
    - "53/udp:53/udp"
    cap_add:
    - NET_ADMIN
    volumes:
    - $PWD/dnsmasq.conf:/etc/dnsmasq.conf
    - $PWD/dnsmasqhosts:/etc/dnsmasqhosts
    - $PWD/resolv.dnsmasq:/etc/resolv.dnsmasq

