version: '2'
services:
  elasticsearch:
    build:
      context: elasticsearch/
    container_name: elasticsearch
    volumes:
    - /root/docker-compose/migrate-es/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - /root/docker-compose/migrate-es/elasticsearch-analysis-pinyin:/usr/share/elasticsearch/plugins/elasticsearch-analysis-pinyin
    - /root/docker-compose/migrate-es/ik:/usr/share/elasticsearch/plugins/ik
    - /data:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    container_name: kibana
    ports:
    - "5601:5601"
    networks:
    - elk
    volumes:
    - /root/docker-compose/migrate-es/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
networks:
  elk:
    driver: bridge
