version: '3'
services:
  mongodb34:
    container_name: mongodb-server
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb3.4:/data/db
    restart: always
    networks:
      - mongodb
networks:
  mongodb:
    driver: bridge
