FROM   jenkinsci/jenkins:2.138.1
USER root
ADD ./sources.list  /etc/apt/sources.list
RUN apt-get update && apt-get -y install apt-transport-https ca-certificates curl software-properties-common && \
    curl -fsSL http://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/debian stretch stable" && \
    apt-get install language-pack-zh* && \
    echo "export LANG=zh_CN.UTF-8" >> /etc/profile && \
    echo "deb https://deb.nodesource.com/node_6.x stretch main" > /etc/apt/sources.list.d/nodesource.list && \
    echo "deb-src https://deb.nodesource.com/node_6.x stretch main" >> /etc/apt/sources.list.d/nodesource.list && \
    apt-get -y update && apt-get -y install docker-ce nodejs

RUN apt-get install -y  python-pip  && pip install virtualenv -i https://mirrors.aliyun.com/pypi/simple/
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /logs && chown jenkins:jenkins /logs

USER jenkins
COPY ./plugins.txt /usr/share/jenkins/plugins.txt
COPY ./plugins.txt /usr/share/jenkins/ref/
#RUN /usr/local/bin/install-plugins.sh   /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh  /usr/share/jenkins/plugins.txt

