version: '2'
services:
  ssserver001:
    image: zyfdedh/shadowsocks:latest
    container_name: ssserver001
    ports:
    - '35537:35539'
    restart: always
    volumes:
    - /var/log/shadowsocks.log:/var/log/shadowsocks.log
    command: ["-s 0.0.0.0 -p 35539 -k $password -m rc4-md5 -t 300 --fast-open"]